apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: wordpress
  name: wordpress
spec:
  containers:
  - image: wordpress
    name: wordpress
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

