apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: wp-db
  name: wp-db
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: wp-db
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_PASSWORD
          value: wordpress
        - name: MYSQL_ROOT_PASSWORD
          value: somewordpress
        - name: MYSQL_USER
          value: wordpress
        image: mysql:5.7
        name: wp-db
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: kompose-wpdb-data
      restartPolicy: Always
      volumes:
      - name: kompose-wpdb-data
        persistentVolumeClaim:
          claimName: kompose-wpdb-data
status: {}
