apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: db
    name: db
  spec:
    clusterIP: None
    ports:
    - name: headless
      port: 55555
      targetPort: 0
    selector:
      io.kompose.service: db
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: wordpress
    name: wordpress
  spec:
    ports:
    - name: "8080"
      port: 8080
      targetPort: 80
    selector:
      io.kompose.service: wordpress
  status:
    loadBalancer: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    name: wp-db
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: wp-db
      spec:
        containers:
        - env:
          - name: MYSQL_DATABASE
            value: exampledb
          - name: MYSQL_PASSWORD
            value: examplepass
          - name: MYSQL_RANDOM_ROOT_PASSWORD
            value: "1"
          - name: MYSQL_USER
            value: exampleuser
          image: mysql:5.7
          name: db
          resources: {}
        restartPolicy: Always
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    name: wp-app
  spec:
    replicas: 2
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: wp-app
      spec:
        containers:
        - env:
          - name: WORDPRESS_DB_PASSWORD
            value: examplepass
          - name: WORDPRESS_DB_USER
            value: exampleuser
          - name: WORDPRESS_DB_HOST
            value: db
          - name: WORDPRESS_DB_NAME
            value: exampledb
          image: wordpress
          name: wordpress
          ports:
          - containerPort: 80
          resources: {}
        restartPolicy: Always
  status: {}
kind: List
metadata: {}

